export { default, modalActions, modalSlice } from "./modalSlice";

export enum MODAL {
	ADD_NOTES = "ADD_NOTES",
	PAY_INVOICE = "PAY_INVOICE",
	DELETE_USER = "DELETE_USER",
	ADD_PAYMENT = "ADD_PAYMENT",
	UNPAY_INVOICE = "UNPAY_INVOICE",
	HANDLE_STATUS = "HANDLE_STATUS",
	CHILDREN_SEATS = "CHILDREN_SEATS",
	ASSIGN_BOOKING = "ASSIGN_BOOKING",
	DISABLE_DRIVER = "DISABLE_DRIVER",
	CANCEL_BOOKING = "CANCEL_BOOKING",
	VERIFY_INVOICE = "VERIFY_INVOICE",
	MARKET_TRANSFER = "MARKET_TRANSFER",
	UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
	GENERATE_INVOICE = "GENERATE_INVOICE",
	UNASSIGN_BOOKING = "UNASSIGN_BOOKING",
	CONFIRMATION_FORM = "CONFIRMATION_FORM",
	CONFIRMATION_MODAL = "CONFIRMATION_MODAL",
	EXPORT_TABLE_OPTIONS = "EXPORT_TABLE_OPTIONS",
	GENERATE_ALL_INVOICES = "GENERATE_ALL_INVOICES",
	UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS",
}

export type ModalType = "" | keyof typeof MODAL;

export interface OpenModalState {
	data: any;
	width: any;
	type: ModalType;
	loading?: boolean;
}

export type ModalState = OpenModalState & {
	open: boolean;
};
